additionalRepositories:
  - url: https://github.com/gitpod-io/demo-multi-repo-backend
    # checkoutLocation is relative to /workspaces
    checkoutLocation: backend

workspaceLocation: bilalafzal-ti/main.code-workspace 

image: node:buster
    
tasks:
  - name: backend
    # change working directory as per configured in `checkoutLocation`
    # which is configured above as `/workspaces/backend`
    before: |
      cd ../backend
    init: |
      echo "Hi from backend! :)"
      echo node --version

github:
  prebuilds:
    master: true
    branches: true

