additionalRepositories:
  - url: https://github.com/bilalafzal-ti/multi-repo-test
    # checkoutLocation is relative to /workspaces
    checkoutLocation: second

workspaceLocation: bilalafzal-ti/main.code-workspace 

image: node:buster
    
tasks:
  - name: second
    # change working directory as per configured in `checkoutLocation`
    # which is configured above as `/workspaces/backend`
    before: |
      cd ../second
    init: |
      echo "Hi from second repo! :)"
      echo node --version

github:
  prebuilds:
    master: true
    branches: true

