additionalRepositories:
  - url: https://github.com/gitpod-io/demo-multi-repo-backend
    # checkoutLocation is relative to /workspaces
    checkoutLocation: backend
    
tasks:
  - init: |
      eval $(command gp env -e)
      echo "Hello ${NAMEE}"
      echo "I am a prebuild"
  - command: |
      echo "cmd block"

  - name: backend
    # change working directory as per configured in `checkoutLocation`
    # which is configured above as `/workspaces/backend`
    before: |
      cd ../backend
    init: |
      echo npm install
    command: |
      echo npm run dev

github:
  prebuilds:
    master: true
    branches: true

