image: gitpod/workspace-full@sha256:b50b760ed41e150a3d0a1fb955e238a3110d3cb186f65c0a6a735f762e8229b9
 

tasks:
  - name: multi-repo-test
    command: echo "1. Main configuration file's task running"

github:
  prebuilds:
    master: true
    branches: true

