image: devfactory/workspace-full@sha256:78a18718ef2585b6dd2cbea45c5d12f95fb3af6e3f983668e6ea39d847b27284
arch: arm

tasks:
  - name: multi-repo-test
    command: echo "1. Main configuration file's task running"

