additionalRepositories:
  - url: https://github.com/bilalafzal-ti/multi-repo-test
    # checkoutLocation is relative to /workspaces
    checkoutLocation: multi-repo-test

image: gitpod/workspace-full:b50b760ed41e150a3d0a1fb955e238a3110d3cb186f65c0a6a735f762e8229b9

workspaceLocation: bilalafzal-ti/main.code-workspace 
    
# tasks:
#   - name: multi-repo-test
#     command: gp repo bilalafzal-ti/multi-repo-test

tasks:
  - name: multi-repo-test
    command: echo "1. Main configuration file's task running"

github:
  prebuilds:
    master: true
    branches: true

